### ISSUE TITLE
Local images still not found

### ISSUE THREAD

**Issue by magune** [Shreyas-R/lovelace-wallpanel-screensaver#17]
Again, thanks for the new version.

Previosuly, I did manage to get the screensaver to show a local image (stored in www/screensaver/image1.jpeg), using the image_url parameter to point to it.

After playing around with the new version, I have broken this and I can't get the screensaver to find the image again.

I broke it since I tried to use the media library to store a set of images instead, but no matter how I try I cannot make the screensaver find the images in the HA media library either.

I appreciate documentation has now been added regarding local image URL's, but I cannot work out what the default HA location is for the images I have uploaded to the media library.

**Comment by Shreyas-R** [comment]
Suppose you have defined the media directories like the following in HA `configuration.yaml`,
```yaml
homeassistant:
  ...
  media_dirs:
    media: /local-storage/media-dir-1
    media1: /local-storage/media-dir-2
```

Then the HA media-source structure will look something like this,
```
media_source
    └── media
            └── photo1.jpg
            └── photo2.jpg
               ...
    └── media1
            └── folder
                     └── videoY.mp4
                      ...
            └── folder1
                     └── photo1.png
                     └── photo2.png
                     ...
```
Here you can access these media folders and sub-folders in the wallpanel-screensaver config at dashboard config file as given in the docs,
```yaml
wallpanel_screensaver:
  ...
  image_url: 'media-source://media_source/media1/folder1' 
```
or<br>
```yaml
wallpanel_screensaver:
  ...
  image_url: '/media1/folder1' 
```
