### ISSUE TITLE
Info box appearing offscreen after editing info_template

### ISSUE THREAD

**Issue by cngarrison** [Shreyas-R/lovelace-wallpanel-screensaver#19]
I added another line to the wallpanel-screensaver-info box via `info_template`. The change makes the info box about 25% taller. The bottom of the info box will sometimes be off the bottom of the screen, when it's positioned randomly.

**Comment by Shreyas-R** [comment]
In this case, you have to adjust the info box style to support the additional height. Although info box is having hardcoded style, it can be customized which is mentioned in the doc. Since it is hardcoded, the default style config parameter doesn't include `wallpanel-screensaver-info-box` style details in the doc. I'll update the documentation to cover this. 

Meanwhile, here is the default style of `wallpanel-screensaver-info-box` HTML element which you can tweak to support additional height. You can adjust `height: '50%'` based on info box content height for a quick fix.
```yaml
wallpanel_screensaver:
  ...
  ...
  style:
    ...
    ...
    wallpanel-screensaver-info-box:
      margin: '5vh auto auto 5vh'
      padding: '0 0 0 0'
      width: '50%'
      height: '50%'
      fontSize: '8vh'
      fontWeight: 600
      color: '#ffffff'
      text-shadow: '-2px -2px 0 #000000, 2px -2px 0 #000000, -2px 2px 0 #000000, 2px 2px 0 #000000'
```

**Comment by cngarrison** [comment]
@Shreyas-R I did check docs but couldn't see it. 😉 

That `style` snippet is what I need, thanks for that.

**Comment by cngarrison** [comment]
I tried changing the height, both as `%` and `px` value. The info box continues (randomly) to be placed off bottom of the screen. 

```
...
    wallpanel-screensaver-info-box:
      margin: 5vh auto auto 5vh
      padding: 0 0 0 0
      width: 50%
      height: 540px
      fontSize: 8vh
      fontWeight: 600
      color: '#ffffff'
      text-shadow: '-2px -2px 0 #000000, 2px -2px 0 #000000, -2px 2px 0 #000000, 2px 2px 0 #000000'
```

Using browser inspector confirms updated height is being used. 

Any other suggestions? 

Thanks,  Charlie
