### ISSUE TITLE
URL Query Parameters not working in browser mod

### ISSUE THREAD

**Issue by fantnhu** [Shreyas-R/lovelace-wallpanel-screensaver#30]
Hi! Thank you for this wonderful development!
I cast a dashboard to Google Nest Hub.
The URL of the dashboard changes depending on events. For this I use Browser MOD so that the transfer does not stop. This is perfect so far.
However, when the screen saver is active and the dashboard changes, the screen saver is active all the time (This is not good for me). Therefore, when the URL changes in the automation, I added the URL parameter.
The URL changes, the parameter is specified, but the screen saver remains active.

```
service: browser_mod.navigate
data:
  deviceID: 0b97b08d-df6d95e4  _#this is my Google Nest HUB_
  navigation_path: /google-nest-hub-cast/cast-camera?wpss_enabled=false
```

Have any idea? Maybe you could make a service that stops it?

Thank you very much
